spring.application.name=EnglishInterlocutorBackend
server.port=8080

yandex.folder-id=${YANDEX_FOLDER_ID}
yandex.api-key=${YANDEX_API_KEY}
yandex.gpt.url=https://llm.api.cloud.yandex.net/foundationModels/v1/completion

